spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDB?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
